version: '3.8'
services:
  db:
    restart: always
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:5432
    volumes:
      - ./.data_storage/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
